####################################################
# Service Configuration
####################################################

SERVICE_NAME="nginx"

####################################################
# Health Check
####################################################

HEALTH_URL="http://localhost"

####################################################
# Reports
####################################################

REPORT_DIR="../reports"

####################################################
# Wait Time (seconds)
####################################################

WAIT_TIME=5

####################################################
# Log Files
####################################################

NGINX_ERROR_LOG="/var/log/nginx/error.log"